### ISSUE TITLE
编译后分发到CDH，程序启动一直报错

### ISSUE THREAD

**Issue by A-little-bit-of-data** [EvenGui/flink-parcel-master#3]
有两套集群，jar包一样，之前是官方分配的parcel 是6.X的  程序能正常跑。现在用的是5.X，能在cdh上正常分发激活，但是程序启动就报错

log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.

------------------------------------------------------------
 The program finished with the following exception:

org.apache.flink.client.deployment.ClusterDeploymentException: Couldn't deploy Yarn session cluster
	at org.apache.flink.yarn.AbstractYarnClusterDescriptor.deploySessionCluster(AbstractYarnClusterDescriptor.java:387)
	at org.apache.flink.client.cli.CliFrontend.runProgram(CliFrontend.java:251)
	at org.apache.flink.client.cli.CliFrontend.run(CliFrontend.java:205)
	at org.apache.flink.client.cli.CliFrontend.parseParameters(CliFrontend.java:1008)
	at org.apache.flink.client.cli.CliFrontend.lambda$main$10(CliFrontend.java:1081)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1920)
	at org.apache.flink.runtime.security.HadoopSecurityContext.runSecured(HadoopSecurityContext.java:41)
	at org.apache.flink.client.cli.CliFrontend.main(CliFrontend.java:1081)
Caused by: org.apache.flink.yarn.AbstractYarnClusterDescriptor$YarnDeploymentException: The YARN application unexpectedly switched to state FAILED during deployment. 
Diagnostics from YARN: Application application_1628838734188_0031 failed 2 times due to AM Container for appattempt_1628838734188_0031_000002 exited with  exitCode: 1
For more detailed output, check application tracking page:http://uat-nn-01:8088/proxy/application_1628838734188_0031/Then, click on links to logs of each attempt.
Diagnostics: Exception from container-launch.
Container id: container_e44_1628838734188_0031_02_000001
Exit code: 1
Stack trace: ExitCodeException exitCode=1: 
	at org.apache.hadoop.util.Shell.runCommand(Shell.java:604)
	at org.apache.hadoop.util.Shell.run(Shell.java:507)
	at org.apache.hadoop.util.Shell$ShellCommandExecutor.execute(Shell.java:789)
	at org.apache.hadoop.yarn.server.nodemanager.DefaultContainerExecutor.launchContainer(DefaultContainerExecutor.java:213)
	at org.apache.hadoop.yarn.server.nodemanager.containermanager.launcher.ContainerLaunch.call(ContainerLaunch.java:302)
	at org.apache.hadoop.yarn.server.nodemanager.containermanager.launcher.ContainerLaunch.call(ContainerLaunch.java:82)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

Container exited with a non-zero exit code 1
Failing this attempt. Failing the application.
If log aggregation is enabled on your cluster, use this command to further investigate the issue:
yarn logs -applicationId application_1628838734188_0031
	at org.apache.flink.yarn.AbstractYarnClusterDescriptor.startAppMaster(AbstractYarnClusterDescriptor.java:1043)
	at org.apache.flink.yarn.AbstractYarnClusterDescriptor.deployInternal(AbstractYarnClusterDescriptor.java:509)
	at org.apache.flink.yarn.AbstractYarnClusterDescriptor.deploySessionCluster(AbstractYarnClusterDescriptor.java:380)

yarn logs -applicationId application_1628838734188_0031
 INFO client.ConfiguredRMFailoverProxyProvider: Failing over to rm68
/tmp/logs/root/logs/application_1628838734188_0031 does not exist.
Log aggregation has not completed or is not enabled.

是编译好的包还需要什么操作么？

**Comment by EvenGui** [comment]
集群开启了Kerberos还是没有开启，检查一下Enable Kerberos Authentication 这个参数，如果集群开启了Kerberos，记得要勾选按钮
